spring.application.name=foodProject
spring.datasource.url=jdbc:mysql://localhost:3306/foodproject
spring.datasource.username=root
spring.datasource.password=1nfotel1ndia
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


#spring.application.name=foodProject
#spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
#spring.datasource.username=${DB_USER}
#spring.datasource.password=${DB_PASSWORD}

razorpay.key=rzp_test_xcoman15SogwMC
razorpay.secret=d9hGUSVJRZHm1cZCeYtgjX7t


twilio.account-sid=ACeb85b1d7be75dad089411764d34a1264
twilio.auth-token=18852b06cd7bb744a3befb7bb0490447
twilio.phone-number=+12315253463
